### ISSUE TITLE
Change color of "MakeDataRecord Public/non public" button according to the status

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#100]
Change the color of the button when changing the status of a record from Non Public to Public. For example, the button "Make DataRecord Public" could be red and the button "Make DataRecord Non Public" could be blue. Right now, this  button does not stand over the others and  it is easy to forget that you need to take care about the status of your record. It will be very helpful a color code.

**Comment by blafuentevalverde** [comment]
outdated
