### ISSUE TITLE
Name Field in Image field is no displayed in Record View when the field is empty

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#101]
When an Image field is empty, it does not display the Name of the field in Record View. It just says "Image not Found" . The name of the field needs to be displayed. Moreover, should we remove the message "Image not found" and just leave the field empty?

![image](https://cloud.githubusercontent.com/assets/10182413/9228162/12ed495e-40cc-11e5-97af-75d794fbd8ca.png)

**Comment by ajpires** [comment]
Thought I had fixed this before, but definitely fixed in commit db256c5
