### ISSUE TITLE
Message denying to download a PDF Reference file from Test Results view

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#102]
When a reference has a non-public PDF associated to it (See CheMin-References, for example), a non-login user cannot see the link to download the file inside the record. However, that user can see the link in the Text Result table. 

![image](https://cloud.githubusercontent.com/assets/10182413/9239979/2ccfbdd0-4116-11e5-8227-af69c66efbc1.png)

If the non-login user click on that link to try to download the file, it gets this message:

{"r":403,"t":"html","d":{"html":"<h2>Permission Denied<\/h2>"}}

Whether the non-login user should not see the link to the non-public files from that table or the message that denied the access should be more clear.

**Comment by ajpires** [comment]
Oops, forgot to mention that this was fixed in commit e3fe91c
