### ISSUE TITLE
Markdown Datafields need some sort of HTML validation...

### ISSUE THREAD

**Issue by ajpires** [OpenDataRepository/data-publisher#111]
The Markdown plugin can handle legitimate HTML like `<b><i><center>Identification</center></i></b>` without a problem, but apparently we need something to locate/deal with bad HTML like...

`<center><b><h1><i><u>Sample Collection Timing</u></i></h1></b>`
`<B><I><CENTER>Identification<B><I><CENTER>`

There are at least two people that have done that at the moment...it's an issue because apparently a markdown datafield with that kind of bad HTML somehow manages to affect every single datafield on the page by inserting some number of additional `<b><i>` tags inside every subsequent datafields' HTML structures on the page.

This breaks multiple jQuery blocks that rely on parent() chains...Radio fields in Record behave erratically at the very least, and I wouldn't be surprised if there are other places with more hidden side-effects.

**Comment by blafuentevalverde** [comment]
outdated

**Comment by ajpires** [comment]
Unfortunately, this looks like it's still a problem...

**Comment by ajpires** [comment]
fixed (again) by commit 0b542cd
