### ISSUE TITLE
Bulk/CSV Exporter

### ISSUE THREAD

**Issue by natestone** [OpenDataRepository/data-publisher#13]
Export CSV from search results.  Related to #11 - should export legacy IDs and internal IDs so the re-import can update appropriate records.

I suggest using data tables jQuery to facilitate export.

**Comment by natestone** [comment]
Also related to #5 - user should select columns they want to export.

**Comment by ajpires** [comment]
Probably going to require further fixes/enhancements, but commit c8cc2c5 contains what should be a stable attempt at this
