### ISSUE TITLE
Modify display of Single/Multiple selection or radio datafields in Advanced Search

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#143]
It is hard to see which options belong to each datafield when there are 2 or more selection or radio datafields together in the list. See for example Advanced Search in PLRP database:

![image](https://cloud.githubusercontent.com/assets/10182413/10778982/3f3b30ea-7ccf-11e5-9538-d0ba87f6dabf.png)

**Comment by ajpires** [comment]
Tweaked in commit 6b5af7d
