### ISSUE TITLE
Rework actions with TrackedJobs to not automatically redirect to the "Active Jobs" list

### ISSUE THREAD

**Issue by ajpires** [OpenDataRepository/data-publisher#149]
...theoretically, CSV Import/Export, Mass Edit, and Fieldtype Migration shouldn't redirect to the "Active Jobs" page, but should display a progress indicator on the same page...or maybe make something in the "bar" towards the top of the page?

The redirection itself isn't the problem, as none of the previously mentioned actions should really remain on the same page...but I guess the "Active Jobs" page is more of a "Completed Jobs" page...have to scroll through quite a few finished options that you don't care about to get the one you do want.

**Comment by blafuentevalverde** [comment]
outdated
