### ISSUE TITLE
Add "Show all records" to search results page

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#158]
Currently, the dropdown list restricts the user to seeing maximum 100 record per page. Add the option to "Show all records" (either for Short Results or Test Results). If the user wants to see 110 records, it would be more practical to see all of them at once instead of a page with 100 and another one with 10. 

![image](https://cloud.githubusercontent.com/assets/10182413/11185727/01ddbbfa-8c33-11e5-8010-fcb3a47bf302.png)

**Comment by blafuentevalverde** [comment]
outdated
