### ISSUE TITLE
URL layout needs a lot of work

### ISSUE THREAD

**Issue by ajpires** [OpenDataRepository/data-publisher#168]
Several things that are currently on the back-burner...
- the "search_slug" part of the URL e.g. "chemin" in http://odr.io/chemin only directs to initial search page...it does nothing on any other page since everything else is loaded via AJAX
- many URLs are too long... http://beta.opendatarepository.org/admin#/results/view/1/dt_id=1 for instance could have at least the "results" part cut out pretty easily
- may not really be able to do much about this, but the search key in the URL string feels kludgy...at the very least could cut out the "dt_id=X" part if the "search_slug" gets fixed to behave more intuitively...
- ability to access datarecords by external id/name datafield...right now you have no choice but to use the search features so ODR can locate its internal id number
- ability to download files/images without using ODR's internal id number if possible...coupled with the previous item, this would be exceptionally helpful for people/services only interested in the uploaded files

**Comment by blafuentevalverde** [comment]
outdated
