### ISSUE TITLE
Delete created users by ADMIN

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#18]
The ADMIN user cannot delete users from his/her own list of users. Only a SUPER ADMIN can do it. If SUPER ADMIN deletes a user, ADMIN can still see it in the list but cannot delete.

**Comment by natestone** [comment]
Alex and I have discussed this option.  We have a solution in progress.  We will allow admins to delete/disassociate users from the data types they administer.
