### ISSUE TITLE
Add new box at the bottom of the template

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#185]
When adding a new box to a template, instead of showing up at the top of the template, it should be added at the end, so you don't need to move it all the way down.

**Comment by ajpires** [comment]
Hmm, tricky.  I was under the impression that the current system is "better" from a user interface perspective...clicking the icon causes a new "box" to show up at the top of the page, immediately providing feedback to the action the user performed.  On the other hand, it makes sense that the user would want it to show up at the bottom of the page...designing from the top of the page towards the bottom is probably going to be the most common approach.

Forcing the page to automatically scroll to the newly created "box" is undesirable...so if the current behavior gets changed and new "boxes" end up being added to the bottom of the template, then some sort of floating notification would probably be needed (which ODR has no capacity to do right now...)

**Comment by blafuentevalverde** [comment]
outdated
