### ISSUE TITLE
"List databases" page needs to remember the # entries selected

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#188]
By default it only shows 10 entries. If user selects 50, the system should remember that selection and makes it default.

<img width="343" alt="screen shot 2016-09-13 at 9 11 13 am" src="https://cloud.githubusercontent.com/assets/10182413/18481788/686a3aa4-7992-11e6-8bcb-b4db07706056.png">

**Comment by ajpires** [comment]
Can't locate the exact commit for the original "fix", but commit 27487fc greatly reduced the need for this paging.
