### ISSUE TITLE
"Add user" button in "List of Users" page

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#189]
Although you can add new users by going to the "User Management" menu, it could be useful to have in the "List of Users" page a button at the top of the screen (next to "Show deleted users") to add a new user.
<img width="603" alt="screen shot 2016-09-13 at 9 18 37 am" src="https://cloud.githubusercontent.com/assets/10182413/18481947/1a6a36d2-7993-11e6-8aab-5ac215fd9dbd.png">

**Comment by ajpires** [comment]
Already added in commit 483dce0
