### ISSUE TITLE
User Preference for Multiple-value upload

### ISSUE THREAD

**Issue by natestone** [OpenDataRepository/data-publisher#19]
From: Rich Keller -->   Multiple-value-uploading - handling it with some sort of convention that you define would be better than nothing at all.  E.g. Use of the '|' as a separator within a CSV element.  Better yet, it could be a configuration/preferences setting as to which character should be used as a multi-value separator

**Comment by ajpires** [comment]
Forgot about this one...was dealt with in commit 574da25
