### ISSUE TITLE
Unable to render child/linked datatypes when a parent datatype has a render plugin

### ISSUE THREAD

**Issue by ajpires** [OpenDataRepository/data-publisher#193]
As a result of the necessary changes made in commit 0cbd316, the array entries required to render child/linked datatypes are no longer passed to a render plugin.

This could be "fixed" rather easily, but it's probably better if I instead make another iteration over the logic/theory behind the current rendering system.  For instance, the decision I originally made to have the datatype/datarecord array entries be flattened (i.e. parent entity on same level of array as child entity) instead of nested...

**Comment by natestone** [comment]
The changes made in that commit need to be reversed.  We _cannot_ include the linked data in the cached array.  If we do this, we have to do queries to figure out what items are linking to a record when that linked record changes and expire them all.

Instead, the linked data should all be independently cached records and should be pulled from the cache when a data record is loaded.  This is a quick process and requires only one query.

Changes like this need to be discussed.  I _never_ want to have to expire records.  The only time a record should expire is:

1) when a user modifies that _individual_ record
2) when a user bulk-modifies a bunch of records.

Even template changes should not result in expiring records.  The template should just be updated and if our system is working properly, the template will drive the display and extra fields in the record will be displayed or not displayed as needed.  Technically, you could re-query on that page load, but it's not really even necessary.

Including the linked data means we will display incorrect pages unless we actively seek and expire pages - that is against the ideal design.

**Comment by ajpires** [comment]
Fixed in commit ff74992
