### ISSUE TITLE
Nate's Gripe Log

### ISSUE THREAD

**Issue by natestone** [OpenDataRepository/data-publisher#196]
Adding Radio Options
  * Flickers all the time
  * Clicking add option messes up the form resulting in fatal exception

Search - useless
  * Need ability to list child template fields or the search is useless...
Properties Box
  * Save dialog appears constantly - timing is a disaster

Link Records
  * Link seems to only appear after page reload when trying to create link in display template editor
  * Search flow is not acceptable

Linked Dropdowns/Change choices on selection.

**Comment by blafuentevalverde** [comment]
outdated
