### ISSUE TITLE
JavaScript error message rework

### ISSUE THREAD

**Issue by ajpires** [OpenDataRepository/data-publisher#20]
On the php side, error messages being returned need to be standardized and cleaned up...on the javascript side, error messages need to be handled by something other than alert()

**Comment by natestone** [comment]
Would really like to convert these to a "growl"-style notification.  The notifications would appear as a modal in the browser and would either time-out and disappear on their own or would be closable by the user.

Ideally, we would have them time out on their own, but have some way to view the last error (i.e.: last error stored in user session so they can call it up at any time).

**Comment by ajpires** [comment]
Investigate whether addError() functionality http://api.symfony.com/2.3/Symfony/Component/Form/Form.html#method_addError would be useful when dealing with Symfony forms
