### ISSUE TITLE
Modified by/created by in Advanced search

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#21]
In "Modify by" and "Created by" fields in "Advanced Search" you select from a list of users. Currently, for all users with a login, the list displays the whole list of users in the system. In the case of an ADMIN or lower access users, this list should only show the users that have permissions for the DataType/s that the login user can access to.

**Comment by ajpires** [comment]
Should be dealt with in commit e45c9f2
