### ISSUE TITLE
Comments plugin Public/non-public

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#22]
The public/non-public icon in the Comments plugin doesn´t work well. Sometimes is red but the comment is public and sometimes is blue but non-public. Here the public/non-public works different. If a comment is not public, even if I am login, I cannot see it until I go to Edit record. It is a bit confusing because you don´t know if you are making it public to everybody (even if the record is non-public) or only for login users.

**Comment by natestone** [comment]
This is really an enhancement due to the way the system works.  We will need to move to a fully dynamic system to do this and are researching that.

**Comment by ajpires** [comment]
Fixed as a result of branch 1.5.1
