### ISSUE TITLE
Problem RESET search

### ISSUE THREAD

**Issue by blafuentevalverde** [OpenDataRepository/data-publisher#221]
In Search, click on Reset clean the selected search items in "Advanced Search" and the "Search for" box but it doesn't reset the search results.

**Comment by blafuentevalverde** [comment]
Also, when I deselect an option in advanced search and click search again, I don't get any results (I should get back the entire list of records). I click again on same option (i know I have to get 2 results) and Search is empty. Something breaks after the first search. I am using CheMin dataset, Chemin Cell field.

**Comment by blafuentevalverde** [comment]
So you have to click on Search after clicking on Reset.  Could we make itso the user doesn't need to Click on Search? It is not intuitive.

**Comment by ajpires** [comment]
fixed in commit 4b5e759
