### ISSUE TITLE
Only one Search result opens full record and makes Search box disappear from screen 

### ISSUE THREAD

**Issue by blafuentevalverde** [OpenDataRepository/data-publisher#222]
In CheMin database, I selected "Chemin Cell = 12b Mylar" and opens Cumberland record, and the Search Box on the left disappeared. No way to get back to the view with Search options on the left and Search results on the Right.

![image](https://user-images.githubusercontent.com/55704329/67228349-e964b200-f3ed-11e9-8542-5a5aa71d7852.png)

**Comment by ajpires** [comment]
fixed in commit 4b5e759
