### ISSUE TITLE
problem with Design Records view Theme Styling settings when scrolling down

### ISSUE THREAD

**Issue by blafuentevalverde** [OpenDataRepository/data-publisher#226]
Impossible to scroll down to the bottom of the Theme Styling column. 
![Screenshot (479)](https://user-images.githubusercontent.com/55704329/67833092-e4b09580-faa0-11e9-9fcd-b0695570b84f.png)

**Comment by ajpires** [comment]
Unfortunately, there's no way this can get resolved for the upcoming rollout...it's part of the myriad of problems with this page (see #213 for more)

**Comment by ajpires** [comment]
removed in commit 1812ecb
