### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by benharvie** [OpenDataRepository/data-publisher#237]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@peter17) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by natestone** [comment]
A security.md file has been added.  Thank you for the notification.

**Comment by peter17** [comment]
@natestone Thanks for creating the `SECURITY.md` file! Could you please review my submission on huntr.dev? You should have received two emails from them on the last few days. Thanks in advance! Best regards
