### ISSUE TITLE
Modify Dated

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#25]
Only selecting the start date and leaving empty the end date works fine, but selecting the start and end date  with the same date, doesn't work properly and it doesn't find any record.

**Comment by ajpires** [comment]
This is probably a result of using mysql BETWEEN when doing any kind of search on datetime datafields

**Comment by ajpires** [comment]
Should be fixed as a result of commit d414f63

**Comment by natestone** [comment]
Just to be clear for Barbara - Alex is closing these when he commits the change, but the change won't appear on the site until the "rollout" that is listed on the milestone.  We will be rolling every Friday morning.  So, you'll see the change then.
