### ISSUE TITLE
Markdown field text box

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#31]
When you select markdown field from the property box, the empty text-box doesn't show up until you click again in the field and the property box refreshes/updates . It should show up right after you select that type of field without having to click in the field again.

**Comment by ajpires** [comment]
Specifically...changing to/from file/image/markdown fieldtypes all require a reload of that right slideout

**Comment by ajpires** [comment]
Fixed in commit 0a8f47d
