### ISSUE TITLE
Search header in Results/Record ignoring sorting

### ISSUE THREAD

**Issue by ajpires** [OpenDataRepository/data-publisher#32]
1) Do any search for a datatype that uses table display instead of shortresults display
2) Sort the table by any criteria
3) View any datarecord

The next/prev buttons on the search header act as if the list hasn't been sorted

**Comment by natestone** [comment]
I assume this is the search header on the record page.  So, you'll need to store the sorted search or do all sorting server-side and then pass back the "sorted" array to the page.

**Comment by ajpires** [comment]
Fixed in commit 181fe40
