### ISSUE TITLE
Mass Edit for Admin users

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#33]
Give to Admin users the ability to Mass Edit a list of records

**Comment by natestone** [comment]
Is this just a request for a permissions change?  I'm not sure when the nature of the issue is since we have mass edit as a function already.

**Comment by barbaralafuente** [comment]
Only Super Admin can do Mass Update but Super Admin cannot give permissions for Mass Update to other users.

**Comment by ajpires** [comment]
Fixed in commit a179e61
