### ISSUE TITLE
Datatype deletion isn't thorough enough

### ISSUE THREAD

**Issue by ajpires** [OpenDataRepository/data-publisher#34]
Deleting a Datatype needs to also delete all Datarecords of that Datatype...while I'm at it, might as well switch deletion stuff to use native SQL to avoid timeouts due to Doctrine.

Might need to look into manually creating log entries for the deleted objects...

**Comment by natestone** [comment]
Is doctrine causing the timeouts? Is it due to hydrating a bunch of objects in a loop?

**Comment by natestone** [comment]
Also might need to queue the jobs to beanstalk.  That would be annoying.

**Comment by ajpires** [comment]
Fixed as a result of branch 1.5.1, can't find exactly where.
