### ISSUE TITLE
Datafield names in XML Export

### ISSUE THREAD

**Issue by ajpires** [OpenDataRepository/data-publisher#35]
Apparently I never modified the XML name generation functions to output valid XML...it's still allowing tag names like
&lt;Don´t_USE._History_TBR&gt;
&lt;Size_cm^3^_NOT_USE!&gt;
&lt;Appraisal_$&gt;

**Comment by natestone** [comment]
Yes - those need to be sanitized and the original should be stored in an attribute.  

<Don´t_USE.History_TBR>  => <Dont_USE.History_TBR title="Don´t_USE.History_TBR">

May need to refer to XML spec to ensure that is a valid way to do it.  It could be that CDATA wrappers would be required to really allow any text in the attribute.

**Comment by ajpires** [comment]
Outputted names for XML elements should be mostly valid as of commit 01c34f0 (at least as far as basic ascii is concerned)...but issues like duplicated XML element names, no numbers at beginning of element names, or illegal UTF-8 characters are going to need a UI for users to detect/display/resolve them...

**Comment by ajpires** [comment]
Still eventually need an interface to set XML-safe names, but added a work-around in commit c3d18ba to identify datafields by id for now.
