### ISSUE TITLE
Button Issue

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#4]
Button "Select All" in linking datarecords interface doesn´t work.

**Comment by natestone** [comment]
It would be best if you put the description in the description field and made the issue subject something like "Button Issue".   I have modified the bug to be more readable in the interface.

**Comment by barbaralafuente** [comment]
Ok, sorry about that. I didnt find out how to label it yet.

**Comment by natestone** [comment]
Alex has fixed and released code that addresses this bug.
