### ISSUE TITLE
No upload link after file deletion

### ISSUE THREAD

**Issue by natestone** [OpenDataRepository/data-publisher#42]
From Bob:
 
_I deleted a cif file from a CheMinCifs record. (I did not like the name of the file that was being viewed, and wanted it to have a more generic name related to the record). So I deleted it, but now there is no link to allow me to upload a new one.
I suspect that I can leave the record, come back in again, and then upload a new file. But I should not have to do this.
Bob_

![unnamed](https://cloud.githubusercontent.com/assets/4010562/7668910/f997da6a-fc23-11e4-9d53-4d0572c6a13e.png)

**Comment by ajpires** [comment]
Was only an issue with datafields that only permitted a single file/image upload...fixed in commit 62db5c6.
