### ISSUE TITLE
Need ability to set whether default of public or non-public

### ISSUE THREAD

**Issue by ajpires** [OpenDataRepository/data-publisher#43]
right now it defaults to non-public...

**Comment by natestone** [comment]
What does this one mean?  Default all newly added fields to "public"? 

I would say that is a security issue and should not be allowed.  All fields should be explicitly set to public by the admin - that way someone is always accountable. 

I recommend against this enhancement unless we have supporting evidence that it is needed.  Inherently, it breaks the chain of trust that the data is "curated".

**Comment by natestone** [comment]
I've read Bob and Barbara's comments.  I can see defaulting the field to public, but I think defaulting the record is hazardous.

That said, originally we had a "public" setting on the data record fields table to allow the defaulting of field instances on the record.  Anyway, that's where it should go.

I think setting whether fields in a record display by default (or their associated files, etc.) is fine, but I worry about defaulting records to public.  It could easily cause data to be issued improperly and breaks the curated aspect of the data.
