### ISSUE TITLE
Slowness due to object hydration possibly?

### ISSUE THREAD

**Issue by natestone** [OpenDataRepository/data-publisher#48]
Could also be due to too many queries.

Here is a screenshot of timeline for reference:
![voila_capture 2015-05-19_01-55-37_pm](https://cloud.githubusercontent.com/assets/4010562/7710066/4877dc36-fe2f-11e4-85c0-2cfb780bccd9.png)

**Comment by natestone** [comment]
I'll investigate and then create a new task when cause is known.

**Comment by natestone** [comment]
source URL:
http://odr.io/app_dev.php/edit/record/114963/datatype_id=175?_=1432056948728

**Comment by ajpires** [comment]
Official speedup originally commited in 0c3162a.
