### ISSUE TITLE
DataTables instances need to watch for changes to TextResults columns

### ISSUE THREAD

**Issue by ajpires** [OpenDataRepository/data-publisher#49]
...right now, they throw an error if a field is removed from the table, and don't show the new field.  Both issues are fixed by a page refresh to get the updated column list, but that needs to happen dynamically.

**Comment by natestone** [comment]
Not sure I'm following this one - is this only occurring for existing searches when a user modifies the database behind it?

It may be too low a priority to look into at this point if that is the case.

**Comment by ajpires** [comment]
Specifically...

1) user 1 brings up a list of Datarecords on a Datatype using Textresults, with columns A, B, C
2) user 2 removes column C from the Textresults layout for that Datatype
3) user 1 attempts to load a different page and/or sort the list of Datarecords...he'll now get a "fatal error" from Datatables because of a mismatch in the number of columns, and will have no idea why because it's not his fault.

**Comment by ajpires** [comment]
Fixed in commit 181fe40
