### ISSUE TITLE
Multiple Record Views

### ISSUE THREAD

**Issue by natestone** [OpenDataRepository/data-publisher#6]
Allow user to build custom record view.  Could be a copy of the display template system that allows the user to remove fields or add them to the view.

Example would be the IMA mineral list.  Default record view includes references.  We need to be able to create a custom view of mineral information only and a custom view of reference information only.  That way, a RRUFF record can have the mineral info at the top and the related reference info at the bottom of the record.

**Comment by blafuentevalverde** [comment]
outdated
