### ISSUE TITLE
DecimalValue field uses integer for base

### ISSUE THREAD

**Issue by ajpires** [OpenDataRepository/data-publisher#60]
...so for instance when the number 27.96722222 is stored in a DecimalValue field, the base becomes 2,796,722,222, which is larger than allowed...

Also, need to apply validation to IntegerValue to prevent the same issue...

**Comment by natestone** [comment]
Might need to use strings.  Then we can have any arbitrary precision we need.  That would be strange though.  We need to research the best way to do this.

**Comment by natestone** [comment]
Also, why is 2 billion larger than allowed for an integer?  You should be using 'bigint' which would allow 10^18 instead of 10^9

**Comment by ajpires** [comment]
Should be completely fixed as of commit 4c916e4
