### ISSUE TITLE
Short/medium/long text number of characters always 32 in Info

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#61]
Same number of characters (32) is given in the info provided for the three field types in Properties (? icon). 

![image](https://cloud.githubusercontent.com/assets/10182413/8010628/945a9726-0b66-11e5-990f-691788685ef9.png)

**Comment by ajpires** [comment]
Actually was an issue with changing fieldtypes...fixed in commit 03b9827
