### ISSUE TITLE
Username and Email in "User Profile"

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#70]
Username becomes the Email when entering the email information, even if you have entered other Username in the "Username" field. Either the Username is chosen by the user using "Username" field or we impose that Email is the username for all users (removing then the "Username" field).

**Comment by natestone** [comment]
I prefer removing the username field - we log in to all other sites with email and email addresses are inherently unique.  I know Bob won't like it, but all of the 3rd party authentication systems use email address as the login ID (OpenID, FaceBook, etc.).

**Comment by barbaralafuente** [comment]
Good for me. It is easier than having to memorize another username.

**Comment by natestone** [comment]
Alex - please hide the username field from the users (and admins on the forms, etc).  Allow email logins only.

**Comment by ajpires** [comment]
Done in commit 45ed706
