### ISSUE TITLE
Markdown in Map to datafield during import

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#71]
When selecting the fields during the import in UAMM, in the selection list you can see 5 fields called "New field". I believe that these fields correspond to Markdown fields, which have not name. If this is the reason, remove Markdown from this list.

![image](https://cloud.githubusercontent.com/assets/10182413/8523386/6586a7ee-23f5-11e5-8335-5a45e0653649.png)

**Comment by ajpires** [comment]
Not sure which commit actually fixed it, but this longer appears to be an issue as of commit e3cc9a4
