### ISSUE TITLE
Need datafield layout history for design templates

### ISSUE THREAD

**Issue by ajpires** [OpenDataRepository/data-publisher#72]
...because there's currently no way to keep track of field names or fieldtypes that a datafield used to have

**Comment by natestone** [comment]
Soft delete needs to be used.  It will save every change in the database and allow you to revert.

So, instead of updating a record, you copy the record, delete the old one, change the value, then save the new one.

**Comment by natestone** [comment]
The database currently supports soft-delete in many tables and we need to switch to use it everywhere.  That way we can pull up a record as it was at any time in the past.  This applies not to just layout history but the record history itself.

**Comment by blafuentevalverde** [comment]
outdated
