### ISSUE TITLE
Bad display of images when Images per row >1 

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#77]
Image field doesn't display the images correctly when selecting more that 1 image per row.

![image](https://cloud.githubusercontent.com/assets/10182413/8762346/9c763e1a-2d2b-11e5-9664-9e0345993458.png)

![image](https://cloud.githubusercontent.com/assets/10182413/8762350/aa02e948-2d2b-11e5-8e07-f6b74bde3449.png)

**Comment by natestone** [comment]
We may just turn off this feature.  It really doesn't make sense from a UI perspective to have a gallery that shows 2 images at a time.  If they are just "gallery" images, one at a time or a display with thumbnails across the bottom would be best.

If two images are required, it is implied that the images have different meanings or information and should probably be two image fields displayed side-by-side.

**Comment by blafuentevalverde** [comment]
outdated
