### ISSUE TITLE
Problems uploading images 

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#78]
Sometimes when the uploading is completed, you cannot see the file or the image. If you try to upload it again, you get 2 images, even if the Image field doesn't allow multiple uploads. Other times, after the uploading, the image shows up twice and when you refresh the page, the image disappeared... In the image, I only upload a file and it showed up double.

![image](https://cloud.githubusercontent.com/assets/10182413/8766806/8e9833fe-2dfb-11e5-9e40-778341120c93.png)

**Comment by natestone** [comment]
We'll investigate.  Sometimes it's easy to accidentally tie the upload action to the upload form multiple times.  Also, a progress indicator or similar will help.  We can look into adding that.

**Comment by ajpires** [comment]
Should be fixed as a result of commit b1a1fe5
