### ISSUE TITLE
Need to be able to set Datatype display_type field per link

### ISSUE THREAD

**Issue by ajpires** [OpenDataRepository/data-publisher#82]
...right now, you're restricted to a single display_type per datatype, which isn't flexible enough if multiple datatypes link to a single datatype

**Comment by natestone** [comment]
Can you clarify this one?  Is it the ability to display a single datatype using different views on a record (i.e. mineral name data at the top of the page and references at the bottom).

If so, I believe we are waiting for fully dynamic page rendering to implement this.  Caching many display types is prohibitive of this upgrade.

**Comment by ajpires** [comment]
Fixed as a result of changes made during branch 1.5.1
