### ISSUE TITLE
Graph plugin display problems

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#89]
If you upload a xy file to be plotted by a graph plugin and you keep the file private, the graph displays correctly until you use "Switch to dinamic graph" . When you come back to Static plot, the plot is not displayed any more. You need to go to Edit Record and make the file public to be able to see the plot in View Mode.

If you don't use "Switch to dinamic plot" you don't need to make the file public to see it.

**Comment by natestone** [comment]
I'll be looking at the graph plugin a bit this month (August).  We expect to add a lot of options and will fix this issue.  It's also related to the system not being fully dynamic.

**Comment by ajpires** [comment]
Graph plugin able to deal with non-public files as a result of the changes made for commit b0b40c6
