### ISSUE TITLE
Change design of Plot zoom area in graph plugin

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#90]
When users use Dynamic Chart, most of the time they get confused because 2 plots show up, the actual xy plot in the top, and the plot for the zoom in the bottom. Change the design (box around the bottom plot?) so it is clear that the bottom graph is a zoom tool. See for example CrystalSleuth

![image](https://cloud.githubusercontent.com/assets/10182413/8946640/e096795c-3546-11e5-9d89-6b775142145f.png)

**Comment by natestone** [comment]
I think some labeling and an icon with instructions could help a lot.   I also think it's a familiarity issue - it's pretty similar to the crystal sleuth version.  I'll work on making it more clear.

**Comment by ajpires** [comment]
Reworked as of commit b0b40c6
