### ISSUE TITLE
Error creating New Data Type

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#91]
I created a new Data Type, I used the same Short and Long name (CheMin-Frames). After accepting the error, the datatype was created.

![image](https://cloud.githubusercontent.com/assets/10182413/8946821/f8962bfe-3548-11e5-8129-5d6054b7816f.png)

I deleted the Data Type and I created a new one with same name. I didn't get any error.

**Comment by ajpires** [comment]
I see that the tweak in commit 3b5cae9 did me no good with catching this problem...best guess I have is that it's somehow attempting to create two datatypes instead of just one.  Will look into.
