### ISSUE TITLE
"Display As" in Child Type forced to be "List" for non Login user

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#92]
Login users can see the multiples entries in a child as it is set in the datatype template. Non login users ALWAYS see the multiple entries in a Child displayed as a LIST, independently of what it is selected in the template. Moreover, the List display usually doesn't work for many Childs making the data very hard to read.

**Comment by natestone** [comment]
This should be solved as part of our migration to fully dynamic pages.  Alex is working on the migration currently.  It will allow us to deal with everyone's permissions in real time with no issues due to caching.

**Comment by ajpires** [comment]
Fixed as a result of the Theme restructuring done on branch 1.5.1
