### ISSUE TITLE
Add "Return to Search Results" button in Mass Edit interface

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#93]
Add "Return to Search Return"  in Mass Edit page to be able to return to the search result after "Save Changes"

![image](https://cloud.githubusercontent.com/assets/10182413/8965011/aa4d6e9a-35dd-11e5-866a-7ec4ef816c73.png)

**Comment by ajpires** [comment]
Done in commit ea2ff61 ...added one to CSVExport as well.
