### ISSUE TITLE
Comments about "Add New User"

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#96]
When I am creating a new user, if I click on the email field (without writing anything), a password automatically shows up in the password field:

![image](https://cloud.githubusercontent.com/assets/10182413/9041458/f815644c-39bc-11e5-95a6-48ae228b0ffd.png)

When I write something in the email filed, whatever was in the password disappears. It looks weird so see something on the password field when you just click on the email field.

After you fill out all the fields, it is not straight forward that you need to click on "Check" to be able to see the "SAVE" button. For example, the other day, I knew that there were not more users with that emails so I didn't click on Check and also, as before the info was saving automatically, and I didn't see SAVE button, I thought that my new user was saved automatically... Obviously, I lost all the info and the new user was not created.

My suggestion is that you can make visible the SAVE button all the time but only make it active (blue) after you click "Check" (which turns inactive) . At least, the user knows that something has to be done to make active the button "SAVE" in order to save the new user.

**Comment by ajpires** [comment]
Leaving the issue open to remind myself to research the autocomplete/autofill problem.

The other suggestions, however, I did implement in commmit 137565e

**Comment by ajpires** [comment]
...forgot to close this after doing the research on the autocomplete/autofill problem.  I can't do anything about it currently...website developers wanting to unilaterally disable it for "security reasons", and certain browser developers unilaterally forcing it to be enabled for "security reasons"...a rather heated internet fight.
