### ISSUE TITLE
Delete last record in a DataType

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#98]
After deleting the LAST record in a datatype, the user should be re -directed to some page, maybe to the List of Record page? Right now, the screen just turns white.

![image](https://cloud.githubusercontent.com/assets/10182413/9125777/f04da0f0-3c58-11e5-9b44-1864c31ec138.png)

**Comment by ajpires** [comment]
Fixed in commit 743bf14
